services:
  - type: web
    name: spender-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: games/spender/Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
