"""Generate spender-core/src/cards.rs from the Python engine's card/noble tables.

Single source of truth: games/spender/ai/az/engine.py builds COST/PTS/BONUS/LEVEL_OF/NOBLE_REQ/
NOBLE_PTS/CARD_NAME/NOBLE_NAME from games/spender/main.py. We dump them verbatim as Rust consts so
the Rust port can NEVER drift from the Python deck. Re-run after any card-data change.

Run from anywhere:  python spender-core/tools/gen_cards.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))   # spender-core/tools -> repo root
sys.path.insert(0, REPO)
os.environ.setdefault("SPENDER_AZ_MODEL", "none")

from games.spender.ai.az import engine as E  # noqa: E402


def _rows(rows):
    return ",\n    ".join("[" + ", ".join(str(x) for x in r) + "]" for r in rows)


def _flat(xs):
    return ", ".join(str(x) for x in xs)


def _strs(xs):
    return ", ".join('"' + s + '"' for s in xs)


nc, nn = E.N_CARDS, E.N_NOBLES
out = [
    "// AUTO-GENERATED by spender-core/tools/gen_cards.py — DO NOT EDIT.",
    "// Source: games/spender/main.py card/noble data via engine._build_tables().",
    "// Color order: white=0, blue=1, green=2, red=3, black=4 (gold=5 has no card cost).",
    "",
    f"pub const N_CARDS: usize = {nc};",
    f"pub const N_NOBLES: usize = {nn};",
    "",
    f"pub const COST: [[i32; 5]; {nc}] = [\n    {_rows(E.COST)},\n];",
    f"pub const PTS: [i32; {nc}] = [{_flat(E.PTS)}];",
    f"pub const BONUS: [usize; {nc}] = [{_flat(E.BONUS)}];",
    f"pub const LEVEL_OF: [i32; {nc}] = [{_flat(E.LEVEL_OF)}];",
    "",
    f"pub const NOBLE_REQ: [[i32; 5]; {nn}] = [\n    {_rows(E.NOBLE_REQ)},\n];",
    f"pub const NOBLE_PTS: [i32; {nn}] = [{_flat(E.NOBLE_PTS)}];",
    "",
    f"pub const CARD_NAME: [&str; {nc}] = [{_strs(E.CARD_NAME)}];",
    f"pub const NOBLE_NAME: [&str; {nn}] = [{_strs(E.NOBLE_NAME)}];",
    "",
]

dst = os.path.abspath(os.path.join(HERE, "..", "src", "cards.rs"))
with open(dst, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")
print(f"wrote {dst}: {nc} cards, {nn} nobles")
