"""Generate spender-core/src/turns_table.rs from turns_table.json (+ turns_table_21.json).

The estimated_turns_remaining horizon reads these (cards, points, gems) -> avg-turns-left tables. Embed
them as Rust consts so WASM needs no file IO and the lookup is identical (row ORDER is preserved for the
NN tie-break — Python picks the first-in-insertion-order nearest cell).

Run:  python spender-core/tools/gen_turns.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
AZ = os.path.abspath(os.path.join(HERE, "..", "..", "games", "spender", "ai", "az"))


def load_rows(name):
    path = os.path.join(AZ, name)
    try:
        with open(path) as f:
            data = json.load(f)
    except (FileNotFoundError, ValueError):
        return []
    return data["rows"]


def fmt(rows):
    # (cards:i32, points:i32, gems:i32, turns:f64)
    return ",\n    ".join(f"({r[0]}, {r[1]}, {r[2]}, {float(r[3])!r})" for r in rows)


rows = load_rows("turns_table.json")
rows21 = load_rows("turns_table_21.json")

out = [
    "// AUTO-GENERATED by spender-core/tools/gen_turns.py — DO NOT EDIT.",
    "// (cards, points, gems) -> avg future main turns. Row order preserved (NN tie-break).",
    "",
    f"pub const TURNS_ROWS: [(i32, i32, i32, f64); {len(rows)}] = [\n    {fmt(rows)}{',' if rows else ''}\n];",
    "",
    f"pub const TURNS_ROWS_21: [(i32, i32, i32, f64); {len(rows21)}] = [\n    {fmt(rows21)}{',' if rows21 else ''}\n];",
    "",
]
dst = os.path.abspath(os.path.join(HERE, "..", "src", "turns_table.rs"))
with open(dst, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")
print(f"wrote {dst}: {len(rows)} rows (15pt), {len(rows21)} rows (21pt)")
