"""Box Puzzles — the daily box. One new box a day, one attempt each.

THE DAY TURNS AT MIDNIGHT US PACIFIC, daylight saving included (PDT from the second
Sunday of March, 02:00, to the first Sunday of November, 02:00). The rule is computed
here rather than read from `zoneinfo` because neither the Windows dev boxes nor the
slim prod image ship a time zone database, and the US rule has not moved since 2007.

THE BOX IS GENERATED BY THE SERVER, WITH REAL RANDOMNESS, AND STORED. The repo is
public, so a committed list of future boxes, or a generator seeded from the date
alone, would hand anyone tomorrow's box and its minimum. `box_daily` holds each day's
box, its minimum and one shortest line; only a FINISHED day's minimum and line ever
leave the server. A background filler keeps a few days generated ahead, so midnight
never waits on the generator; a request that finds today missing (the first deploy,
an empty dev DB) generates it on the spot under a short budget.

HOW A BOX IS MADE (measured, 2026-10-05). Random tiles alone are useless: 64% of
random 3-5 colour boards cannot reach any one-colour target, and most of the rest open
in 3-6 presses. So the generator explores EVERYTHING a random board can reach (a few
thousand boards, ~40ms) and only then picks the target, from the corner patterns that
board can actually make. The real bank's mixed targets are all symmetric pairs, so
those are the shapes allowed: one colour, diagonal pairs, top/bottom, left/right.
Then four filters, each one a way a box is bad for a one-attempt race:
  * the minimum is the day's drawn depth, 8..15 (owner's range);
  * EVERY COLOUR MATTERS — graying out any one colour must change the minimum, or that
    colour was decoration;
  * AT MOST `MAX_WAYS` SHORTEST LINES — the real boxes in the same range have a median
    of 28, and a box with thousands can be stumbled through;
  * NO TROPES — LENGTH IS NOT DIFFICULTY. chandler.io's solution-space analysis of every
    Mora Jai box found the long ones are mostly one trick repeated (a centre column
    driving the blues, a centre row shuffled through them). Every shortest line must
    have at most `MAX_TROPE` of its presses covered by ONE repeated motif (a run of 1-4
    presses occurring 3+ times); if any shortest line avoids the repetition, it is not
    forced. Measured (2026-10-06): median share 0.27 in both the real 8-15 boxes and
    generated ones, but generated had the longer tail (worst: 14 presses, 11 of them the
    centre tile); > 0.5 rejects 4 of 80 generated and 1 of 46 real.
A corner-greedy player test was measured too and NOT added: it cannot fire. A player
pressing whatever matches the most corners hit the minimum on <= 0.7% of tries on any
generated box (<= 4.3% on the real ones) and opened them at all on <= 8% (real: <= 30%),
so the generated boxes already resist it better than the designed ones.

ONE ATTEMPT, AND IT ONLY GROWS. An attempt is a list of SEGMENTS: the tile presses
between resets (a reset is a corner button pressed while its corner does not match,
and it puts the box back on its first board). The score is every tile press in every
segment — a reset no longer clears the count — so the server must see the segments,
not one flat list, to replay where each one started. A save is accepted only if it
EXTENDS what is stored (same earlier segments, the stored last one as a prefix), and
an opened box is final. That one rule is both "progress is saved" and "no rewinding".

THEN AS MANY RETRIES AS YOU LIKE, ON A SECOND BOARD (owner's call, 2026-10-06). Once
the attempt has opened the box it may be played again, for the fewest presses, with the
numbered boxes' rules: the count is the presses since the last reset, nothing is saved
mid-solve, and each player keeps their best (a tie keeps the earlier time). The two
boards are FIRST ATTEMPT (`box_daily_attempts`, the race) and BEST ATTEMPT (`box_daily_best`).
The one attempt seeds Best Attempt with its score, so a player who never retries still
has a row there. Retries need the one attempt done first — a retry before it would be
free practice for the race.
"""
from __future__ import annotations

import json
import random
import threading
import time
from datetime import date, datetime, timedelta, timezone

from core.rooms import deal_rng

from boxpuzzles.engine import COLORS, CORNERS, corners_match, press, replay

MIN_DEPTH, MAX_DEPTH = 8, 15
MAX_WAYS = 200
MAX_TROPE = 0.5             # most of a shortest line one repeated motif may cover
STATE_CAP = 40_000          # boards explored per candidate; a bigger board is skipped
MAX_MOVES = 2000            # an attempt longer than this is refused
MAX_SEGMENTS = MAX_MOVES + 1   # the page never starts an empty segment, so a reset costs a press
AHEAD_DAYS = 2              # the filler keeps today + this many days generated
REQUEST_BUDGET = 8.0        # seconds a request may spend generating a missing day
FILLER_BUDGET = 300.0
FILLER_DELAY = 600.0        # the filler's first pass waits this long after arming
FILLER_EVERY = 3600.0
BOARD_SIZE = 20

ACTIVE = tuple(c for c in COLORS if c != "GY")


# ── the day ──────────────────────────────────────────────────────────────────
def _nth_sunday(year: int, month: int, n: int) -> date:
    first = date(year, month, 1)
    return first + timedelta(days=(6 - first.weekday()) % 7 + 7 * (n - 1))


def pacific_offset(ts: float) -> int:
    """Hours from UTC to US Pacific at the instant `ts`: -7 in daylight time, else -8."""
    u = datetime.fromtimestamp(ts, timezone.utc)
    start = datetime(*_nth_sunday(u.year, 3, 2).timetuple()[:3], 10, tzinfo=timezone.utc)
    end = datetime(*_nth_sunday(u.year, 11, 1).timetuple()[:3], 9, tzinfo=timezone.utc)
    return -7 if start <= u < end else -8


def pacific_day(ts: float | None = None) -> str:
    ts = time.time() if ts is None else ts
    local = datetime.fromtimestamp(ts, timezone.utc) + timedelta(hours=pacific_offset(ts))
    return local.date().isoformat()


def day_start(day: str) -> float:
    """The UTC instant `day` begins in Pacific time. Midnight is never inside a
    daylight-saving change (those happen at 02:00), so one of the two offsets fits."""
    midnight = datetime.fromisoformat(day).replace(tzinfo=timezone.utc).timestamp()
    for off in (-7, -8):
        t = midnight - off * 3600
        if pacific_offset(t) == off:
            return t
    raise AssertionError(f"no Pacific midnight for {day}")


def next_day(day: str, n: int = 1) -> str:
    return (date.fromisoformat(day) + timedelta(days=n)).isoformat()


# ── the generator ────────────────────────────────────────────────────────────
# Target shapes, as the four corner colours clockwise from the top-left.
SHAPES = (
    lambda a, b: (a, a, a, a),      # one colour
    lambda a, b: (a, b, a, b),      # diagonal pairs (every mixed target in the real bank)
    lambda a, b: (a, a, b, b),      # top / bottom
    lambda a, b: (a, b, b, a),      # left / right
)


def _explore(start: tuple) -> dict | None:
    """Every board `start` can reach, with the depth it is first reached at. None
    past STATE_CAP (a board that big is skipped, not searched)."""
    depth = {start: 0}
    queue = [start]
    for t in queue:
        d = depth[t] + 1
        for i in range(9):
            u = press(t, i)
            if u not in depth:
                depth[u] = d
                queue.append(u)
                if len(depth) > STATE_CAP:
                    return None
    return depth


def _reaches_within(start: tuple, target: tuple, limit: int) -> bool:
    if corners_match(start, target):
        return True
    seen = {start}
    layer = [start]
    for _ in range(limit):
        nxt = []
        for t in layer:
            for i in range(9):
                u = press(t, i)
                if u in seen:
                    continue
                if corners_match(u, target):
                    return True
                seen.add(u)
                nxt.append(u)
        if not nxt:
            return False
        layer = nxt
    return False


def shortest_lines(start: tuple, target: tuple, cap: int = MAX_WAYS + 1) -> list[list[int]]:
    """The distinct shortest press sequences that open the box, up to `cap` of them
    (a layered BFS keeping every parent one layer up, then walked back)."""
    start = tuple(start)
    if corners_match(start, target):
        return [[]]
    parents: dict[tuple, list] = {start: []}
    layer = [start]
    while layer:
        nxt: dict[tuple, list] = {}
        for t in layer:
            for i in range(9):
                u = press(t, i)
                if u not in parents:
                    nxt.setdefault(u, []).append((t, i))
        parents.update(nxt)
        goals = [u for u in nxt if corners_match(u, target)]
        if goals:
            out: list[list[int]] = []

            def back(u, tail):
                if len(out) >= cap:
                    return
                if not parents[u]:
                    out.append(tail[::-1])
                    return
                for t, i in parents[u]:
                    back(t, tail + [i])
            for g in goals:
                back(g, [])
            return out
        layer = list(nxt)
    return []


def motif_share(line: list[int]) -> float:
    """The largest share of `line` covered by one motif — a run of 1-4 presses —
    repeated 3+ times without overlapping. 0 when nothing repeats that often."""
    n, best = len(line), 0.0
    for k in range(1, 5):
        for s in range(n - k + 1):
            motif = line[s:s + k]
            occ, i = 0, 0
            while i <= n - k:
                if line[i:i + k] == motif:
                    occ += 1
                    i += k
                else:
                    i += 1
            if occ >= 3:
                best = max(best, occ * k / n)
    return best


def _targets(tiles: tuple, depth: dict) -> dict[tuple, int]:
    """Each allowed target this board can make -> its minimum, within 8..15."""
    first: dict[tuple, int] = {}
    for s, d in depth.items():
        k = tuple(s[c] for c in CORNERS)
        if k not in first:
            first[k] = d
    present = sorted(set(tiles) - {"GY"})
    out = {}
    for a in present:
        for b in present:
            for i, shape in enumerate(SHAPES):
                if (i == 0) != (a == b):
                    continue
                t = shape(a, b)
                m = first.get(t)
                if m is not None and MIN_DEPTH <= m <= MAX_DEPTH:
                    out[t] = m
    return out


def _good(tiles: tuple, target: tuple, m: int) -> list[int] | None:
    """The box's least repetitive shortest line if it passes every filter, else None."""
    for c in set(tiles) - {"GY"}:
        grayed = tuple("GY" if x == c else x for x in tiles)
        if _reaches_within(grayed, target, m) and not _reaches_within(grayed, target, m - 1):
            return None             # that colour changed nothing
    lines = shortest_lines(tiles, target)
    if not 1 <= len(lines) <= MAX_WAYS:
        return None
    line = min(lines, key=motif_share)
    return line if motif_share(line) <= MAX_TROPE else None


def _candidate(rng: random.Random) -> tuple:
    k = rng.choice((3, 4, 4, 5, 5))
    cols = rng.sample(ACTIVE, k - 1) + (["GY"] if rng.random() < 0.6 else [rng.choice(ACTIVE)])
    return tuple(rng.choice(cols) for _ in range(9))


def generate(rng: random.Random, want: int, budget: float = FILLER_BUDGET,
             pause: float = 0.0) -> dict:
    """A box whose minimum is `want` presses, or — once `budget` seconds have gone —
    the closest good box found so far. `pause` sleeps between candidates (the filler
    runs beside the game sockets and should leave them the interpreter)."""
    deadline = time.monotonic() + budget
    best = None
    while True:
        tiles = _candidate(rng)
        depth = _explore(tiles)
        if depth is not None:
            options = _targets(tiles, depth)
            ranked = sorted(options.items(), key=lambda kv: (abs(kv[1] - want), kv[0]))
            for target, m in ranked[:3]:
                if best is not None and abs(m - want) >= abs(best[2] - want):
                    break
                line = _good(tiles, target, m)
                if line is not None:
                    best = (tiles, target, m, line)
                    break
        if best is not None and (best[2] == want or time.monotonic() > deadline):
            tiles, target, m, line = best
            # the stored line (yesterday's replay) is the least repetitive shortest one
            assert len(line) == m and corners_match(replay(tiles, line), target)
            return {"tiles": list(tiles), "target": list(target), "minimum": m, "solution": line}
        if pause:
            time.sleep(pause)


# ── storage ──────────────────────────────────────────────────────────────────
def init_daily_db(conn) -> None:
    cur = conn.cursor()
    cur.execute("""
    CREATE TABLE IF NOT EXISTS box_daily (
        day TEXT PRIMARY KEY,
        tiles TEXT NOT NULL,
        target TEXT NOT NULL,
        minimum INTEGER NOT NULL,
        solution TEXT NOT NULL,
        created_at REAL NOT NULL
    )""")
    cur.execute("""
    CREATE TABLE IF NOT EXISTS box_daily_attempts (
        user_id TEXT NOT NULL,
        day TEXT NOT NULL,
        segments TEXT NOT NULL,
        moves INTEGER NOT NULL,
        solved_at REAL,
        updated_at REAL NOT NULL,
        PRIMARY KEY (user_id, day)
    )""")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_box_daily_board "
                "ON box_daily_attempts (day, solved_at, moves)")
    cur.execute("""
    CREATE TABLE IF NOT EXISTS box_daily_best (
        user_id TEXT NOT NULL,
        day TEXT NOT NULL,
        moves INTEGER NOT NULL,
        solved_at REAL NOT NULL,
        PRIMARY KEY (user_id, day)
    )""")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_box_daily_best_board "
                "ON box_daily_best (day, moves, solved_at)")
    # Attempts opened before Best Attempt existed seed it too (a no-op once they have).
    cur.execute("INSERT OR IGNORE INTO box_daily_best (user_id, day, moves, solved_at) "
                "SELECT user_id, day, moves, solved_at FROM box_daily_attempts WHERE solved_at IS NOT NULL")
    conn.commit()


def _codes(s: str) -> list[str]:
    return [s[i:i + 2] for i in range(0, len(s), 2)]


def get_day(conn, day: str) -> dict | None:
    cur = conn.cursor()
    cur.execute("SELECT tiles, target, minimum, solution FROM box_daily WHERE day=?", (day,))
    row = cur.fetchone()
    if row is None:
        return None
    return {"day": day, "tiles": _codes(row[0]), "target": _codes(row[1]),
            "minimum": row[2], "solution": json.loads(row[3])}


def store_day(conn, day: str, box: dict) -> dict:
    """Write `box` for `day` unless one is already there; returns whichever is stored.
    INSERT OR IGNORE, so a request and the filler racing for the same day agree."""
    cur = conn.cursor()
    cur.execute("INSERT OR IGNORE INTO box_daily (day, tiles, target, minimum, solution, created_at) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (day, "".join(box["tiles"]), "".join(box["target"]), box["minimum"],
                 json.dumps(box["solution"]), time.time()))
    conn.commit()
    return get_day(conn, day)


_gen_lock = threading.Lock()


def ensure_day(conn, day: str, budget: float = REQUEST_BUDGET, pause: float = 0.0) -> dict:
    """The box for `day`, generating it first if it does not exist yet."""
    have = get_day(conn, day)
    if have is not None:
        return have
    with _gen_lock:                 # one generator at a time; the rest wait for its row
        have = get_day(conn, day)
        if have is not None:
            return have
        # Unseeded in production (unpredictable). GAMES_DEAL_SEED, which the render gate
        # sets, makes a day's box reproducible there.
        rng = deal_rng(mode=f"boxdaily|{day}")
        box = generate(rng, rng.randint(MIN_DEPTH, MAX_DEPTH), budget=budget, pause=pause)
        return store_day(conn, day, box)


_filler_started = False


def start_filler(get_db_conn) -> None:
    """Keep the next AHEAD_DAYS days generated, from a daemon thread started by the
    first daily request (so importing this module, or a test, starts nothing). It
    waits FILLER_DELAY before its first pass: a fresh process — a deploy, or the render
    gate's backend — has today already and should not spend its first minutes here."""
    global _filler_started
    if _filler_started:
        return
    _filler_started = True

    def loop():
        time.sleep(FILLER_DELAY)
        while True:
            today = pacific_day()
            for n in range(1, AHEAD_DAYS + 1):
                conn = get_db_conn()
                try:
                    ensure_day(conn, next_day(today, n), budget=FILLER_BUDGET, pause=0.02)
                except Exception:  # noqa: BLE001 - the request path still generates on demand
                    pass
                finally:
                    conn.close()
            time.sleep(FILLER_EVERY)

    threading.Thread(target=loop, name="boxpuzzles-daily", daemon=True).start()


# ── attempts ─────────────────────────────────────────────────────────────────
class Refused(ValueError):
    """The attempt cannot be saved as sent. `status` is the HTTP code to answer with."""

    def __init__(self, message: str, status: int = 400):
        super().__init__(message)
        self.status = status


def _valid_segments(segments) -> list[list[int]]:
    if not isinstance(segments, list) or not segments or len(segments) > MAX_SEGMENTS:
        raise Refused("bad segments")
    total = 0
    for seg in segments:
        if not isinstance(seg, list):
            raise Refused("bad segments")
        for m in seg:
            if not isinstance(m, int) or isinstance(m, bool) or not 0 <= m <= 8:
                raise Refused(f"not a tile: {m!r}")
        total += len(seg)
    if total > MAX_MOVES:
        raise Refused("too many moves")
    return segments


def extends(stored: list[list[int]], new: list[list[int]]) -> bool:
    """True if `new` is `stored` played on: the same finished segments, the stored
    last segment as a prefix of new's, and anything after it."""
    if len(new) < len(stored):
        return False
    k = len(stored) - 1
    if new[:k] != stored[:k]:
        return False
    return new[k][:len(stored[k])] == stored[k]


def load_attempt(conn, user_id: str, day: str) -> dict | None:
    cur = conn.cursor()
    cur.execute("SELECT segments, moves, solved_at FROM box_daily_attempts WHERE user_id=? AND day=?",
                (user_id, day))
    row = cur.fetchone()
    if row is None:
        return None
    return {"segments": json.loads(row[0]), "moves": row[1], "solved": row[2] is not None}


def save_attempt(conn, user_id: str, box: dict, segments, opened: bool,
                 now: float | None = None) -> dict:
    """Store the attempt if it extends what is stored. With `opened`, the last segment
    must open the box from its first board, and the attempt becomes final."""
    now = time.time() if now is None else now
    segments = _valid_segments(segments)
    moves = sum(len(s) for s in segments)
    stored = load_attempt(conn, user_id, box["day"])
    if stored is not None and stored["solved"]:
        if stored["segments"] == segments and opened:
            return {**stored, "segments": segments}     # a retried final post: same answer
        raise Refused("today's box is already open", status=409)
    if stored is not None and not extends(stored["segments"], segments):
        raise Refused("that is not the attempt on record", status=409)
    if opened and not corners_match(replay(box["tiles"], segments[-1]), box["target"]):
        raise Refused("that does not open the box")
    cur = conn.cursor()
    blob = json.dumps(segments, separators=(",", ":"))
    solved_at = now if opened else None
    if stored is None:
        cur.execute("INSERT INTO box_daily_attempts (user_id, day, segments, moves, solved_at, updated_at) "
                    "VALUES (?, ?, ?, ?, ?, ?)", (user_id, box["day"], blob, moves, solved_at, now))
    else:
        cur.execute("UPDATE box_daily_attempts SET segments=?, moves=?, solved_at=?, updated_at=? "
                    "WHERE user_id=? AND day=?", (blob, moves, solved_at, now, user_id, box["day"]))
    conn.commit()
    if opened:
        _keep_best(conn, user_id, box["day"], moves, now)
    return {"segments": segments, "moves": moves, "solved": opened}


def _keep_best(conn, user_id: str, day: str, moves: int, now: float) -> dict:
    cur = conn.cursor()
    cur.execute("SELECT moves FROM box_daily_best WHERE user_id=? AND day=?", (user_id, day))
    row = cur.fetchone()
    if row is None:
        cur.execute("INSERT INTO box_daily_best (user_id, day, moves, solved_at) VALUES (?, ?, ?, ?)",
                    (user_id, day, moves, now))
    elif moves < row[0]:
        cur.execute("UPDATE box_daily_best SET moves=?, solved_at=? WHERE user_id=? AND day=?",
                    (moves, now, user_id, day))
    else:
        return {"best": row[0], "improved": False}
    conn.commit()
    return {"best": moves, "improved": True}


def save_retry(conn, user_id: str, box: dict, moves, now: float | None = None) -> dict:
    """A retry that opened the box: `moves` (the presses since its last reset) must
    open it from the first board. Kept if it beats the player's best. Refused until
    their one attempt has opened the box."""
    now = time.time() if now is None else now
    stored = load_attempt(conn, user_id, box["day"])
    if stored is None or not stored["solved"]:
        raise Refused("open today's box first", status=403)
    if (not isinstance(moves, list) or len(moves) > MAX_MOVES
            or any(not isinstance(m, int) or isinstance(m, bool) or not 0 <= m <= 8 for m in moves)):
        raise Refused("bad moves")
    if not corners_match(replay(box["tiles"], moves), box["target"]):
        raise Refused("that does not open the box")
    return _keep_best(conn, user_id, box["day"], len(moves), now)


# The two boards: which table, and whether a row must be a finished one.
_BOARDS = {"first": ("box_daily_attempts", "AND a.solved_at IS NOT NULL"),
           "best": ("box_daily_best", "")}


def _ranked(conn, which: str, day: str, minimum: int, user_id: str | None, reveal: bool, size: int) -> dict:
    table, finished = _BOARDS[which]
    cur = conn.cursor()
    cur.execute(f"""
        SELECT a.user_id, u.name, a.moves FROM {table} a
        LEFT JOIN users u ON u.id = a.user_id
        WHERE a.day=? {finished}
        ORDER BY a.moves, a.solved_at LIMIT ?""", (day, size))
    entries = []
    for rank, (uid, name, moves) in enumerate(cur.fetchall(), 1):
        e = {"rank": rank, "name": name or "?", "moves": moves}
        mine = bool(user_id) and uid == user_id
        if mine:
            e["you"] = True
        if mine or reveal:
            e["optimal"] = moves <= minimum
        entries.append(e)
    cur.execute(f"SELECT COUNT(*) FROM {table} a WHERE a.day=? {finished}", (day,))
    total = cur.fetchone()[0]
    you = None
    if user_id:
        cur.execute(f"SELECT a.moves, a.solved_at FROM {table} a WHERE a.user_id=? AND a.day=? {finished}",
                    (user_id, day))
        mine = cur.fetchone()
        if mine is not None:
            cur.execute(f"""SELECT COUNT(*) FROM {table} a WHERE a.day=? {finished}
                            AND (a.moves < ? OR (a.moves = ? AND a.solved_at < ?))""",
                        (day, mine[0], mine[0], mine[1]))
            you = {"rank": cur.fetchone()[0] + 1, "moves": mine[0], "optimal": mine[0] <= minimum}
    return {"entries": entries, "total": total, "you": you}


def daily_board(conn, box: dict, user_id: str | None, reveal: bool, size: int = BOARD_SIZE) -> dict:
    """The day's two boards, fewest presses first and the earlier finish first on a
    tie: First Attempt at the top level (where it always was, so a cached page still reads
    it) and Best Attempt under `best`. While the day is live (`reveal` False) the minimum
    stays secret and only the caller's own row says whether it is optimal; once the
    day is over every row does, and the minimum and a shortest line come with it."""
    day, minimum = box["day"], box["minimum"]
    out = {"day": day, **_ranked(conn, "first", day, minimum, user_id, reveal, size),
           "best": _ranked(conn, "best", day, minimum, user_id, reveal, size)}
    if reveal:
        out.update(tiles=box["tiles"], target=box["target"], minimum=minimum, solution=box["solution"])
    return out
